---
- name: Create a .kube directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
    mode: '0755'

#Way to do this with podman_container?
- name: Copy .kubeconfig from microshift container
  ansible.builtin.command: "sudo podman cp microshift:/var/lib/microshift/resources/kubeadmin/kubeconfig {{ ansible_env.HOME }}/.kube/config"
