---
- name: Create tmp directory to store OpenShift client
  ansible.builtin.tempfile:
    state: directory
  register: tempdir_output

- name: Set fact for tmp directory
  ansible.builtin.set_fact:
    tempdir: "{{ tempdir_output.path }}"

- name: Get the OpenShift client
  ansible.builtin.get_url:
  url: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz"
  dest: "{{ tempdir }}"

- name: Untar the OpenShift client
  ansible.builtin.unarchive:
    src: "{{ tempdir }}/openshift-client-linux.tar.gz"
    dest: "{{ tempdir }}"
    remote_src: yes

- name: Copy oc binary to /usr/local/bin
  ansible.builtin.copy:
    src: "{{ tempdir }}/{{ item }}"
    dest: /usr/local/bin/
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  become: yes
  loop:
    - kubectl
    - oc

